// Database of LaTeX Math Symbols mapped to Unicode for preview

export type SymbolCategory =
  'greek' |
  'operators' |
  'relations' |
  'arrows' |
  'delimiters' |
  'misc' |
  'cyrillic' |
  'misc_text' |
  'fontawesome' |
  'special';

export interface LatexSymbol {
  cmd: string;
  char: string; // Unicode representation for UI
  name?: string;
  fontFamily?: string;
}

export const SYMBOLS_DB: Record<SymbolCategory, LatexSymbol[]> = {
  greek: [
    { cmd: '\\alpha', char: 'α' }, { cmd: '\\beta', char: 'β' }, { cmd: '\\gamma', char: 'γ' },
    { cmd: '\\delta', char: 'δ' }, { cmd: '\\epsilon', char: 'ϵ' }, { cmd: '\\zeta', char: 'ζ' },
    { cmd: '\\eta', char: 'η' }, { cmd: '\\theta', char: 'θ' }, { cmd: '\\iota', char: 'ι' },
    { cmd: '\\kappa', char: 'κ' }, { cmd: '\\lambda', char: 'λ' }, { cmd: '\\mu', char: 'μ' },
    { cmd: '\\nu', char: 'ν' }, { cmd: '\\xi', char: 'ξ' }, { cmd: '\\pi', char: 'π' },
    { cmd: '\\rho', char: 'ρ' }, { cmd: '\\sigma', char: 'σ' }, { cmd: '\\tau', char: 'τ' },
    { cmd: '\\upsilon', char: 'υ' }, { cmd: '\\phi', char: 'ϕ' }, { cmd: '\\chi', char: 'χ' },
    { cmd: '\\psi', char: 'ψ' }, { cmd: '\\omega', char: 'ω' },
    // Variants
    { cmd: '\\varepsilon', char: 'ε' }, { cmd: '\\vartheta', char: 'ϑ' }, { cmd: '\\varpi', char: 'ϖ' },
    { cmd: '\\varrho', char: 'ϱ' }, { cmd: '\\varsigma', char: 'ς' }, { cmd: '\\varphi', char: 'φ' },
    { cmd: '\\digamma', char: 'ϝ' },
    // Upper
    { cmd: '\\Gamma', char: 'Γ' }, { cmd: '\\Delta', char: 'Δ' }, { cmd: '\\Theta', char: 'Θ' },
    { cmd: '\\Lambda', char: 'Λ' }, { cmd: '\\Xi', char: 'Ξ' }, { cmd: '\\Pi', char: 'Π' },
    { cmd: '\\Sigma', char: 'Σ' }, { cmd: '\\Upsilon', char: 'Υ' }, { cmd: '\\Phi', char: 'Φ' },
    { cmd: '\\Psi', char: 'Ψ' }, { cmd: '\\Omega', char: 'Ω' }
  ],
  operators: [
    { cmd: '\\pm', char: '±' }, { cmd: '\\mp', char: '∓' }, { cmd: '\\times', char: '×' },
    { cmd: '\\cdot', char: '⋅' }, { cmd: '\\div', char: '÷' }, { cmd: '\\ast', char: '∗' },
    { cmd: '\\star', char: '★' }, { cmd: '\\circ', char: '∘' }, { cmd: '\\bullet', char: '∙' },
    { cmd: '\\oplus', char: '⊕' }, { cmd: '\\ominus', char: '⊖' }, { cmd: '\\otimes', char: '⊗' },
    { cmd: '\\oslash', char: '⊘' }, { cmd: '\\odot', char: '⊙' },
    { cmd: '\\cap', char: '∩' }, { cmd: '\\cup', char: '∪' },
    { cmd: '\\uplus', char: '⊎' }, { cmd: '\\sqcap', char: '⊓' }, { cmd: '\\sqcup', char: '⊔' },
    { cmd: '\\vee', char: '∨' }, { cmd: '\\wedge', char: '∧' }, { cmd: '\\setminus', char: '∖' },
    { cmd: '\\amalg', char: '⨿' }, { cmd: '\\diamond', char: '⋄' }, { cmd: '\\lozenge', char: '◊' },
    { cmd: '\\bigtriangleup', char: '△' }, { cmd: '\\bigtriangledown', char: '▽' },
    { cmd: '\\dagger', char: '†' }, { cmd: '\\ddagger', char: '‡' }, { cmd: '\\wr', char: '≀' },
    { cmd: '\\bigcirc', char: '○' }, { cmd: '\\triangleleft', char: '◁' }, { cmd: '\\triangleright', char: '▷' },
    { cmd: '\\int', char: '∫' }, { cmd: '\\iint', char: '∬' }, { cmd: '\\iiint', char: '∭' }, { cmd: '\\iiiint', char: '⨌' },
    { cmd: '\\oint', char: '∮' },
    { cmd: '\\sum', char: '∑' }, { cmd: '\\prod', char: '∏' }, { cmd: '\\coprod', char: '∐' },
    { cmd: '\\bigcup', char: '⋃' }, { cmd: '\\bigcap', char: '⋂' }, { cmd: '\\bigsqcup', char: '⨆' },
    { cmd: '\\bigwedge', char: '⋀' }, { cmd: '\\bigvee', char: '⋁' },
    { cmd: '\\bigotimes', char: '⨂' }, { cmd: '\\bigoplus', char: '⨁' }, { cmd: '\\bigodot', char: '⨀' },
    { cmd: '\\lim', char: 'lim' },
    { cmd: '\\infty', char: '∞' }, { cmd: '\\to', char: '→' }, { cmd: '\\mapsto', char: '↦' },
    { cmd: '\\partial', char: '∂' }, { cmd: '\\nabla', char: '∇' }, { cmd: '\\prime', char: '′' },
    { cmd: '\\dot{}', char: 'ẋ' }, { cmd: '\\ddot{}', char: 'ẍ' }
  ],
  relations: [
    { cmd: '\\leq', char: '≤' }, { cmd: '\\geq', char: '≥' }, { cmd: '\\equiv', char: '≡' },
    { cmd: '\\sim', char: '∼' }, { cmd: '\\simeq', char: '≃' }, { cmd: '\\approx', char: '≈' },
    { cmd: '\\cong', char: '≅' }, { cmd: '\\neq', char: '≠' }, { cmd: '\\subset', char: '⊂' },
    { cmd: '\\supset', char: '⊃' }, { cmd: '\\subseteq', char: '⊆' }, { cmd: '\\supseteq', char: '⊇' },
    { cmd: '\\sqsubset', char: '⊏' }, { cmd: '\\sqsupset', char: '⊐' }, { cmd: '\\sqsubseteq', char: '⊑' }, { cmd: '\\sqsupseteq', char: '⊒' },
    { cmd: '\\in', char: '∈' }, { cmd: '\\ni', char: '∋' }, { cmd: '\\notin', char: '∉' },
    { cmd: '\\perp', char: '⊥' }, { cmd: '\\parallel', char: '∥' },
    { cmd: '\\preceq', char: '⪯' }, { cmd: '\\succeq', char: '⪰' },
    { cmd: '\\ll', char: '≪' }, { cmd: '\\gg', char: '≫' },
    { cmd: '\\vdash', char: '⊢' }, { cmd: '\\dashv', char: '⊣' }, { cmd: '\\models', char: '⊨' },
    { cmd: '\\bowtie', char: '⋈' }, { cmd: '\\smile', char: '⌣' }, { cmd: '\\frown', char: '⌢' },
    { cmd: '\\asymp', char: '≍' }, { cmd: '\\doteq', char: '≐' }, { cmd: '\\propto', char: '∝' },
    { cmd: '\\mid', char: '∣' }
  ],
  arrows: [
    { cmd: '\\leftarrow', char: '←' }, { cmd: '\\rightarrow', char: '→' }, { cmd: '\\uparrow', char: '↑' },
    { cmd: '\\downarrow', char: '↓' }, { cmd: '\\leftrightarrow', char: '↔' },
    { cmd: '\\Leftarrow', char: '⇐' }, { cmd: '\\Rightarrow', char: '⇒' }, { cmd: '\\Leftrightarrow', char: '⇔' },
    { cmd: '\\longleftarrow', char: '⟵' }, { cmd: '\\longrightarrow', char: '⟶' }, { cmd: '\\longleftrightarrow', char: '⟷' },
    { cmd: '\\Longleftarrow', char: '⟸' }, { cmd: '\\Longrightarrow', char: '⟹' }, { cmd: '\\Longleftrightarrow', char: '⟺' },
    { cmd: '\\iff', char: '⟺' },
    { cmd: '\\mapsto', char: '↦' }, { cmd: '\\longmapsto', char: '⟼' },
    { cmd: '\\hookleftarrow', char: '↩' }, { cmd: '\\hookrightarrow', char: '↪' },
    { cmd: '\\nearrow', char: '↗' }, { cmd: '\\searrow', char: '↘' }, { cmd: '\\swarrow', char: '↙' }, { cmd: '\\nwarrow', char: '↖' },
    { cmd: '\\upharpoonleft', char: '↿' }, { cmd: '\\upharpoonright', char: '↾' },
    { cmd: '\\downharpoonleft', char: '⇃' }, { cmd: '\\downharpoonright', char: '⇂' },
    { cmd: '\\rightleftharpoons', char: '⇌' }, { cmd: '\\leftrightharpoons', char: '⇋' },
    { cmd: '\\curvearrowleft', char: '↶' }, { cmd: '\\curvearrowright', char: '↷' },
    { cmd: '\\circlearrowleft', char: '↺' }, { cmd: '\\circlearrowright', char: '↻' },
    { cmd: '\\twoheadrightarrow', char: '↠' }, { cmd: '\\twoheadleftarrow', char: '↞' },
    { cmd: '\\rightarrowtail', char: '↣' }, { cmd: '\\leftarrowtail', char: '↢' },
    { cmd: '\\looparrowright', char: '↬' }, { cmd: '\\looparrowleft', char: '↫' },
    { cmd: '\\nrightarrow', char: '↛' }, { cmd: '\\nleftarrow', char: '↚' },
    { cmd: '\\nRightarrow', char: '⇏' }, { cmd: '\\nLeftarrow', char: '⇍' }, { cmd: '\\nleftrightarrow', char: '↮' }, { cmd: '\\nLeftrightarrow', char: '⇎' },
    { cmd: '\\multimap', char: '⊸' }, { cmd: '\\rightsquigarrow', char: '⇝' }
  ],
  delimiters: [
    { cmd: '\\{ \\}', char: '{ }' }, { cmd: '\\langle \\rangle', char: '⟨ ⟩' },
    { cmd: '\\lfloor \\rfloor', char: '⌊ ⌋' }, { cmd: '\\lceil \\rceil', char: '⌈ ⌉' },
    { cmd: '| |', char: '| |' }, { cmd: '\\| \\|', char: '‖ ‖' },
    { cmd: '\\ulcorner \\urcorner', char: '⌜ ⌝' }, { cmd: '\\llcorner \\lrcorner', char: '⌞ ⌟' }
  ],
  misc: [
    { cmd: '\\forall', char: '∀' }, { cmd: '\\exists', char: '∃' }, { cmd: '\\nexists', char: '∄' },
    { cmd: '\\therefore', char: '∴' }, { cmd: '\\because', char: '∵' },
    { cmd: '\\neg', char: '¬' }, { cmd: '\\lnot', char: '¬' },
    { cmd: '\\land', char: '∧' }, { cmd: '\\lor', char: '∨' },
    { cmd: '\\top', char: '⊤' }, { cmd: '\\bot', char: '⊥' },
    { cmd: '\\cdots', char: '⋯' }, { cmd: '\\vdots', char: '⋮' }, { cmd: '\\ddots', char: '⋱' },
    { cmd: '\\vec{}', char: 'v⃗' }, { cmd: '\\hat{}', char: 'â' }, { cmd: '\\bar{}', char: 'ā' },
    { cmd: '\\tilde{}', char: 'ã' }, { cmd: '\\mathbf{}', char: 'v' }, { cmd: '\\mathbb{}', char: 'ℝ' },
    { cmd: '\\det', char: 'det' }, { cmd: '\\dim', char: 'dim' }, { cmd: '\\ker', char: 'ker' },
    { cmd: '\\rank', char: 'rank' }, { cmd: '\\tr', char: 'tr' },
    { cmd: '\\hom', char: 'hom' }, { cmd: '\\angle', char: '∠' }, { cmd: '\\triangle', char: '△' },
    { cmd: '\\perp', char: '⊥' }, { cmd: '\\parallel', char: '∥' },
    { cmd: '\\ell', char: 'ℓ' }, { cmd: '\\Re', char: 'ℜ' }, { cmd: '\\Im', char: 'ℑ' },
    { cmd: '\\aleph', char: 'ℵ' }, { cmd: '\\hbar', char: 'ℏ' }, { cmd: '\\emptyset', char: '∅' },
    { cmd: '\\flat', char: '♭' }, { cmd: '\\natural', char: '♮' }, { cmd: '\\sharp', char: '♯' }
  ],
  cyrillic: [
      { cmd: '\\cyr', char: 'cyr' }
  ],
  misc_text: [
      { cmd: '\\dag', char: '†' }, { cmd: '\\ddag', char: '‡' }, { cmd: '\\S', char: '§' }, { cmd: '\\P', char: '¶' },
      { cmd: '\\copyright', char: '©' }, { cmd: '\\pounds', char: '£' }
  ],
      fontawesome: [
    { cmd: '\\faIcon{500px}', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAccessibleIcon', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAccusoft', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAddressBook', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAddressCard', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAdjust', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAdn', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAdversal', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAffiliatetheme', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAlarmClock', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAlgolia', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAlignCenter', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAlignJustify', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAlignLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAlignRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAmazon', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAmazonPay', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAmbulance', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAmericanSignLanguageInterpreting', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAmilia', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAnchor', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAndroid', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAngellist', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAngleDoubleDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAngleDoubleLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAngleDoubleRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAngleDoubleUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAngleDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAngleLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAngleRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAngleUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAngrycreative', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAngular', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAppStore', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAppStoreIos', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faApper', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faApple', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faApplePay', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faArchive', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltCircleDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltCircleLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltCircleRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltCircleUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltFromBottom', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltFromLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltFromRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltFromTop', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltSquareDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltSquareLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltSquareRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltSquareUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltToBottom', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltToLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltToRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltToTop', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowAltUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowCircleDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowCircleLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowCircleRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowCircleUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowFromBottom', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowFromLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowFromRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowFromTop', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowSquareDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowSquareLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowSquareRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowSquareUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowToBottom', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowToLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowToRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowToTop', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrows', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowsAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowsAltH', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowsAltV', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowsH', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faArrowsV', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAssistiveListeningSystems', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAsterisk', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAsymmetrik', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAudible', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAudioDescription', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faAutoprefixer', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAvianex', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAviato', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faAws', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBackward', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBadge', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBadgeCheck', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBalanceScale', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBan', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBandcamp', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBarcode', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBars', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBath', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBatteryBolt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBatteryEmpty', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBatteryFull', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBatteryHalf', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBatteryQuarter', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBatterySlash', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBatteryThreeQuarters', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBed', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBeer', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBehance', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBehanceSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBell', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBellSlash', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBicycle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBimobject', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBinoculars', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBirthdayCake', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBitbucket', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBitcoin', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBity', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBlackTie', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBlackberry', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBlind', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBlogger', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBloggerB', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBluetooth', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBluetoothB', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBold', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBolt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBomb', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBook', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBookmark', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBraille', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBriefcase', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBrowser', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBtc', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBug', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBuilding', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBullhorn', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBullseye', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBuromobelexperte', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faBus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faBuysellads', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCalculator', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCalendar', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCalendarAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCalendarCheck', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCalendarEdit', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCalendarExclamation', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCalendarMinus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCalendarPlus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCalendarTimes', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCamera', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCameraAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCameraRetro', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCar', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretCircleDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretCircleLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretCircleRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretCircleUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretSquareDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretSquareLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretSquareRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretSquareUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCaretUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCartArrowDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCartPlus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCcAmazonPay', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCcAmex', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCcApplePay', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCcDinersClub', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCcDiscover', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCcJcb', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCcMastercard', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCcPaypal', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCcStripe', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCcVisa', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCentercode', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCertificate', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChartArea', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChartBar', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChartLine', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChartPie', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCheck', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCheckCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCheckSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronCircleDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronCircleLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronCircleRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronCircleUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronDoubleDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronDoubleLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronDoubleRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronDoubleUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronSquareDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronSquareLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronSquareRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronSquareUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChevronUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChild', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faChrome', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCircleNotch', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faClipboard', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faClock', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faClone', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faClosedCaptioning', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCloud', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCloudDownload', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCloudDownloadAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCloudUpload', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCloudUploadAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCloudscale', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCloudsmith', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCloudversify', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faClub', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCode', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCodeBranch', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCodeCommit', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCodeMerge', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCodepen', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCodiepie', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCoffee', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCog', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCogs', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faColumns', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faComment', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCommentAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faComments', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCompass', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCompress', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCompressAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCompressWide', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faConnectdevelop', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faContao', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCopy', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCopyright', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCpanel', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCreativeCommons', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCreditCard', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCreditCardBlank', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCreditCardFront', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCrop', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCrosshairs', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCss3', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCss3Alt', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faCube', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCubes', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCut', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faCuttlefish', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDAndD', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDashcube', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDatabase', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faDeaf', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faDelicious', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDeploydog', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDeskpro', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDesktop', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faDesktopAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faDeviantart', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDiamond', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faDigg', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDigitalOcean', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDiscord', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDiscourse', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDochub', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDocker', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDollarSign', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faDotCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faDownload', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faDraft2Digital', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDribbble', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDribbbleSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDropbox', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDrupal', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faDyalog', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faEarlybirds', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faEdge', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faEdit', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEject', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEllipsisH', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEllipsisHAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEllipsisV', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEllipsisVAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEmber', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faEmpire', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faEnvelope', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEnvelopeOpen', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEnvelopeSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEnvira', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faEraser', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faErlang', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faEthereum', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faEtsy', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faEuroSign', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExchange', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExchangeAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExclamation', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExclamationCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExclamationSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExclamationTriangle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExpand', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExpandAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExpandArrows', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExpandArrowsAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExpandWide', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExpeditedssl', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faExternalLink', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExternalLinkAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExternalLinkSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faExternalLinkSquareAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEye', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEyeDropper', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faEyeSlash', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFacebook', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFacebookF', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFacebookMessenger', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFacebookSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFastBackward', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFastForward', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFax', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFemale', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFighterJet', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFile', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileArchive', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileAudio', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileCheck', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileCode', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileEdit', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileExcel', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileExclamation', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileImage', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileMinus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFilePdf', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFilePlus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFilePowerpoint', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileTimes', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileVideo', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFileWord', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFilm', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFilmAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFilter', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFire', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFireExtinguisher', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFirefox', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFirstOrder', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFirstdraft', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFlag', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFlagCheckered', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFlask', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFlickr', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFly', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFolder', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFolderOpen', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFont', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFontAwesome', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFontAwesomeAlt', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFontAwesomeFlag', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFonticons', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFonticonsFi', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFortAwesome', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFortAwesomeAlt', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faForumbee', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faForward', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFoursquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFreeCodeCamp', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFreebsd', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faFrown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faFutbol', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faGamepad', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faGavel', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faGem', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faGenderless', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faGetPocket', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGg', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGgCircle', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGift', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faGit', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGitSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGithub', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGithubAlt', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGithubSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGitkraken', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGitlab', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGitter', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGlassMartini', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faGlide', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGlideG', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGlobe', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faGofore', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGoodreads', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGoodreadsG', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGoogle', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGoogleDrive', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGooglePlay', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGooglePlus', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGooglePlusG', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGooglePlusSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGoogleWallet', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGraduationCap', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faGratipay', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGrav', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGripfire', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGrunt', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faGulp', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faHSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faH1', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faH2', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faH3', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHackerNews', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faHackerNewsSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faHandLizard', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandPaper', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandPeace', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandPointDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandPointLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandPointRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandPointUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandPointer', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandRock', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandScissors', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandSpock', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHandshake', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHashtag', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHdd', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHeading', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHeadphones', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHeart', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHeartbeat', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHexagon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHireAHelper', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faHistory', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHome', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHooli', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faHospital', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHotjar', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faHourglass', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHourglassEnd', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHourglassHalf', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHourglassStart', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faHouzz', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faHtml5', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faHubspot', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faICursor', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faIdBadge', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faIdCard', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faImage', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faImages', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faImdb', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faInbox', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faInboxIn', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faInboxOut', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faIndent', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faIndustry', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faIndustryAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faInfo', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faInfoCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faInfoSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faInstagram', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faInternetExplorer', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faIoxhost', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faItalic', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faItunes', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faItunesNote', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faJackOLantern', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faJenkins', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faJoget', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faJoomla', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faJs', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faJsSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faJsfiddle', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faKey', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faKeyboard', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faKeycdn', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faKickstarter', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faKickstarterK', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faKorvue', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLanguage', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLaptop', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLaravel', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLastfm', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLastfmSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLeaf', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLeanpub', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLemon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLess', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLevelDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLevelDownAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLevelUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLevelUpAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLifeRing', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLightbulb', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLine', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLink', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLinkedin', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLinkedinIn', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLinode', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLinux', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faLiraSign', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faList', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faListAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faListOl', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faListUl', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLocationArrow', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLock', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLockAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLockOpen', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLockOpenAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLongArrowAltDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLongArrowAltLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLongArrowAltRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLongArrowAltUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLongArrowDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLongArrowLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLongArrowRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLongArrowUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLowVision', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faLyft', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMagento', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMagic', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMagnet', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMale', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMap', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMapMarker', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMapMarkerAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMapPin', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMapSigns', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMars', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMarsDouble', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMarsStroke', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMarsStrokeH', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMarsStrokeV', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMaxcdn', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMedapps', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMedium', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMediumM', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMedkit', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMedrt', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMeetup', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMeh', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMercury', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMicrochip', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMicrophone', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMicrophoneAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMicrophoneSlash', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMicrosoft', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMinus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMinusCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMinusHexagon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMinusOctagon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMinusSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMix', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMixcloud', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMizuni', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMobile', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMobileAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMobileAndroid', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMobileAndroidAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faModx', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMonero', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faMoneyBill', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMoneyBillAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMoon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMotorcycle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMousePointer', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faMusic', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faNapster', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faNeuter', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faNewspaper', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faNintendoSwitch', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faNode', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faNodeJs', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faNpm', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faNs8', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faNutritionix', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faObjectGroup', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faObjectUngroup', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faOctagon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faOdnoklassniki', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faOdnoklassnikiSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faOpencart', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faOpenid', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faOpera', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faOptinMonster', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faOsi', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faOutdent', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPage4', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPagelines', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPaintBrush', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPalfed', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPaperPlane', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPaperclip', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faParagraph', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPaste', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPatreon', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPause', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPauseCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPaw', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPaypal', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPen', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPenAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPenSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPencil', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPencilAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPercent', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPeriscope', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPhabricator', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPhoenixFramework', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPhone', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPhoneSlash', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPhoneSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPhoneVolume', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPiedPiper', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPiedPiperAlt', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPiedPiperPp', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPinterest', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPinterestP', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPinterestSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPlane', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPlaneAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPlay', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPlayCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPlaystation', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPlug', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPlus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPlusCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPlusHexagon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPlusOctagon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPlusSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPodcast', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPoo', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPortrait', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPoundSign', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPowerOff', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPrint', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faProductHunt', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPushed', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faPuzzlePiece', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faPython', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faQq', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faQrcode', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faQuestion', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faQuestionCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faQuestionSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faQuora', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faQuoteLeft', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faQuoteRight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRandom', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRavelry', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faReact', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faRebel', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faRectangleLandscape', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRectanglePortrait', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRectangleWide', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRecycle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRedRiver', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faReddit', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faRedditAlien', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faRedditSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faRedo', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRedoAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRegistered', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRendact', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faRenren', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faRepeat', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRepeat1', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRepeat1Alt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRepeatAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faReply', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faReplyAll', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faReplyd', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faResolving', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faRetweet', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRetweetAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRoad', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRocket', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRocketchat', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faRockrms', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faRss', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRssSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRubleSign', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faRupeeSign', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSafari', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSass', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSave', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSchlix', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faScribd', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faScrubber', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSearch', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSearchMinus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSearchPlus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSearchengin', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSellcast', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSellsy', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faServer', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faServicestack', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faShare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShareAll', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShareAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShareAltSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShareSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShekelSign', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShield', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShieldAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShieldCheck', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShip', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShirtsinbulk', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faShoppingBag', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShoppingBasket', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShoppingCart', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faShower', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSignIn', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSignInAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSignLanguage', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSignOut', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSignOutAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSignal', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSimplybuilt', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSistrix', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSitemap', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSkyatlas', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSkype', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSlack', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSlackHash', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSlidersH', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSlidersHSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSlidersV', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSlidersVSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSlideshare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSmile', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSnapchat', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSnapchatGhost', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSnapchatSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSnowflake', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSort', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSortAlphaDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSortAlphaUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSortAmountDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSortAmountUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSortDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSortNumericDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSortNumericUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSortUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSoundcloud', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSpaceShuttle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSpade', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSpeakap', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSpinner', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSpinnerThird', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSpotify', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStackExchange', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faStackOverflow', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faStar', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStarExclamation', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStarHalf', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStaylinked', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSteam', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSteamSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSteamSymbol', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faStepBackward', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStepForward', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStethoscope', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStickerMule', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faStickyNote', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStop', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStopCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStopwatch', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStrava', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faStreetView', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStrikethrough', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faStripe', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faStripeS', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faStudiovinari', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faStumbleupon', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faStumbleuponCircle', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSubscript', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSubway', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSuitcase', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSun', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSuperpowers', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSuperscript', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSupple', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faSync', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faSyncAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTable', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTablet', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTabletAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTabletAndroid', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTabletAndroidAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTachometer', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTachometerAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTag', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTags', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTasks', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTaxi', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTelegram', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faTelegramPlane', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faTencentWeibo', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faTerminal', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTextHeight', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTextWidth', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTh', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faThLarge', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faThList', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faThemeisle', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faThermometerEmpty', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faThermometerFull', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faThermometerHalf', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faThermometerQuarter', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faThermometerThreeQuarters', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faThumbsDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faThumbsUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faThumbtack', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTicket', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTicketAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTimes', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTimesCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTimesHexagon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTimesOctagon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTimesSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTint', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faToggleOff', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faToggleOn', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTrademark', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTrain', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTransgender', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTransgenderAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTrash', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTrashAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTree', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTreeAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTrello', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faTriangle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTripadvisor', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faTrophy', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTrophyAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTruck', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTty', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTumblr', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faTumblrSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faTv', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTvRetro', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faTwitch', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faTwitter', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faTwitterSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faTypo3', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faUber', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faUikit', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faUmbrella', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUnderline', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUndo', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUndoAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUniregistry', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faUniversalAccess', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUniversity', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUnlink', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUnlock', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUnlockAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUntappd', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faUpload', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUsb', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faUsdCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUsdSquare', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUser', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUserAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUserCircle', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUserMd', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUserPlus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUserSecret', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUserTimes', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUsers', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUssunnah', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faUtensilFork', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUtensilKnife', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUtensilSpoon', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUtensils', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faUtensilsAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faVaadin', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faVenus', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faVenusDouble', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faVenusMars', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faViacoin', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faViadeo', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faViadeoSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faViber', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faVideo', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faVimeo', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faVimeoSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faVimeoV', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faVine', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faVk', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faVnv', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faVolumeDown', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faVolumeMute', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faVolumeOff', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faVolumeUp', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faVuejs', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWatch', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faWeibo', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWeixin', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWhatsapp', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWhatsappSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWheelchair', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faWhmcs', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWifi', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faWikipediaW', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWindow', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faWindowAlt', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faWindowClose', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faWindowMaximize', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faWindowMinimize', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faWindowRestore', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faWindows', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWonSign', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faWordpress', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWordpressSimple', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWpbeginner', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWpexplorer', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWpforms', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faWrench', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faXbox', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faXing', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faXingSquare', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faYCombinator', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faYahoo', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faYandex', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faYandexInternational', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faYelp', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faYenSign', char: '', fontFamily: 'Font Awesome 6 Free' },
    { cmd: '\\faYoast', char: '', fontFamily: 'Font Awesome 6 Brands' },
    { cmd: '\\faYoutube', char: '', fontFamily: 'Font Awesome 6 Brands' }
  ],
  special: [
      { cmd: '\\%', char: '%' }, { cmd: '\\#', char: '#' }, { cmd: '\\&', char: '&' }, { cmd: '\\_', char: '_' }
  ]
};
