import { useState } from "react";
import {
  AppShell,
  Group,
  Stack,
  Text,
  ActionIcon,
  Tooltip,
  Button,
  ScrollArea,
  TextInput,
  Badge,
  MantineProvider,
  createTheme,
  Box,
} from "@mantine/core";

// --- [ΑΛΛΑΓΗ 1: Προσθήκη του πραγματικού Editor] ---
// Βεβαιώσου ότι έκανες: npm install @monaco-editor/react
import Editor from "@monaco-editor/react";

import { latexLanguage, latexConfiguration } from "./languages/latex";
import { dataTexDarkTheme } from "./themes/monaco-theme";

import {
  Files,
  Database,
  Search,
  Settings,
  Wand2,
  Play,
  FileCode,
  Table2,
  Columns,
  X,
  ChevronDown,
  TerminalSquare,
  Maximize2,
  MoreVertical,
  ChevronRight,
} from "lucide-react";

// --- Theme Configuration (Mantine) ---
const theme = createTheme({
  primaryColor: "blue",
  defaultRadius: "sm",
  fontFamily: "Inter, sans-serif",
  colors: {
    dark: [
      "#C1C2C5",
      "#A6A7AB",
      "#909296",
      "#5c5f66",
      "#373A40",
      "#2C2E33",
      "#25262b", // dark.6
      "#1A1B1E", // dark.7 (Standard Mantine Dark Background)
      "#141517", // dark.8
      "#101113", // dark.9
    ],
  },
});

// --- Mock Data ---
type SidebarSection = "files" | "search" | "database" | "wizards";

const MOCK_FILES = [
  { name: "document.tex", type: "tex" },
  { name: "preamble.sty", type: "sty" },
  { name: "bibliography.bib", type: "bib" },
];

const MOCK_TABLES = [
  { name: "exercises_algebra", count: 150 },
  { name: "geometry_theorems", count: 45 },
  { name: "physics_problems", count: 89 },
];

const INITIAL_CODE = `\\documentclass{article}
\\usepackage{amsmath}
\\usepackage{tikz}

% Generated by DataTex Wizard
\\begin{document}

  \\section{Εισαγωγή}
  Αυτό είναι ένα παράδειγμα αρχείου LaTeX.
  
  % Example Equation
  $ E = mc^2 $

  \\begin{equation}
     \\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}
  \\end{equation}

\\end{document}`;

// --- Components ---

// 1. Activity Bar
const ActivityBar = ({
  active,
  setActive,
}: {
  active: SidebarSection;
  setActive: (v: SidebarSection) => void;
}) => {
  const items = [
    { icon: Files, label: "Αρχεία", id: "files" },
    { icon: Search, label: "Αναζήτηση", id: "search" },
    { icon: Database, label: "Βάση Δεδομένων", id: "database" },
    { icon: Wand2, label: "Wizards", id: "wizards" },
  ];

  return (
    <Stack
      w={50}
      h="100%"
      align="center"
      gap="md"
      py="md"
      bg="dark.8"
      style={{ borderRight: "1px solid var(--mantine-color-dark-6)" }}
    >
      {items.map((item) => (
        <Tooltip
          label={item.label}
          key={item.id}
          position="right"
          withArrow
          transitionProps={{ duration: 0 }}
        >
          <ActionIcon
            variant={active === item.id ? "filled" : "subtle"}
            color={active === item.id ? "blue" : "gray"}
            size="lg"
            onClick={() => setActive(item.id as SidebarSection)}
            radius="md"
          >
            <item.icon size={22} strokeWidth={1.5} />
          </ActionIcon>
        </Tooltip>
      ))}

      <Box style={{ marginTop: "auto" }}>
        <Tooltip label="Ρυθμίσεις" position="right" withArrow>
          <ActionIcon variant="subtle" color="gray" size="lg">
            <Settings size={22} strokeWidth={1.5} />
          </ActionIcon>
        </Tooltip>
      </Box>
    </Stack>
  );
};

// 2. Sidebar Content
const SidebarContent = ({
  activeSection,
}: {
  activeSection: SidebarSection;
}) => {
  return (
    <Stack gap={0} h="100%" bg="dark.7">
      <Group
        justify="space-between"
        px="xs"
        h={36}
        style={{ borderBottom: "1px solid var(--mantine-color-dark-6)" }}
      >
        <Text size="xs" fw={700} tt="uppercase" c="dimmed">
          {activeSection === "files" && "Explorer"}
          {activeSection === "database" && "DataTex DB"}
          {activeSection === "wizards" && "Wizards"}
          {activeSection === "search" && "Αναζήτηση"}
        </Text>
        <ActionIcon variant="subtle" size="xs" color="gray">
          <MoreVertical size={14} />
        </ActionIcon>
      </Group>

      <ScrollArea style={{ flex: 1 }}>
        {activeSection === "files" && (
          <Stack gap={2} p="xs">
            <Group
              gap={4}
              py={4}
              px={6}
              style={{ cursor: "pointer", borderRadius: 4 }}
              bg="dark.6"
            >
              <ChevronDown size={14} />
              <Text size="xs" fw={700}>
                PROJECT ROOT
              </Text>
            </Group>
            {MOCK_FILES.map((f) => (
              <Group
                key={f.name}
                gap={8}
                pl={24}
                py={4}
                style={{ cursor: "pointer", borderRadius: 4 }}
              >
                <FileCode size={14} color="#4dabf7" />
                <Text size="sm" c="gray.3">
                  {f.name}
                </Text>
              </Group>
            ))}
          </Stack>
        )}

        {/* ... (Υπόλοιπα sidebar sections παραμένουν ίδια) ... */}
        {activeSection === "database" && (
          <Stack gap="md" p="xs">
            <Button
              size="xs"
              leftSection={<Database size={14} />}
              fullWidth
              variant="light"
            >
              Σύνδεση DB
            </Button>
            <Box>
              <Text size="xs" fw={700} c="dimmed" mb="xs">
                TABLES
              </Text>
              {MOCK_TABLES.map((t) => (
                <Group
                  key={t.name}
                  justify="space-between"
                  mb={4}
                  p={4}
                  style={{ cursor: "pointer", borderRadius: 4 }}
                >
                  <Group gap={6}>
                    <Table2 size={14} color="#69db7c" />
                    <Text size="sm" truncate>
                      {t.name}
                    </Text>
                  </Group>
                  <Badge size="xs" variant="outline" color="gray">
                    {t.count}
                  </Badge>
                </Group>
              ))}
            </Box>
          </Stack>
        )}
      </ScrollArea>
    </Stack>
  );
};

// 3. Main Editor Area
const EditorArea = () => {

  return (
    <Stack gap={0} h="100%" w="100%">
      {/* Tabs */}
      <Group
        gap={0}
        bg="dark.8"
        style={{ borderBottom: "1px solid var(--mantine-color-dark-6)" }}
      >
        <Box
          py={8}
          px={12}
          bg="dark.7"
          style={{
            borderTop: "2px solid #339af0",
            borderRight: "1px solid var(--mantine-color-dark-6)",
            cursor: "default",
          }}
        >
          <Group gap={6}>
            <FileCode size={14} color="#4dabf7" />
            <Text size="xs" c="white">
              document.tex
            </Text>
            <ActionIcon size="xs" variant="transparent" color="gray">
              <X size={12} />
            </ActionIcon>
          </Group>
        </Box>
        <Box
          py={8}
          px={12}
          style={{
            cursor: "pointer",
            borderRight: "1px solid var(--mantine-color-dark-6)",
          }}
        >
          <Group gap={6}>
            <Table2 size={14} color="#69db7c" />
            <Text size="xs" c="dimmed">
              data_view.db
            </Text>
            <ActionIcon size="xs" variant="transparent" color="gray">
              <X size={12} />
            </ActionIcon>
          </Group>
        </Box>
      </Group>

      {/* Toolbar */}
      <Group
        h={32}
        px="md"
        bg="dark.7"
        justify="space-between"
        style={{ borderBottom: "1px solid var(--mantine-color-dark-6)" }}
      >
        <Group gap={4}>
          <Text size="xs" c="dimmed">
            DataTex
          </Text>
          <ChevronRight size={12} color="gray" />
          <Text size="xs" c="dimmed">
            src
          </Text>
          <ChevronRight size={12} color="gray" />
          <Text size="xs" c="white">
            document.tex
          </Text>
        </Group>
        <Group gap="xs">
          <Tooltip label="Compile">
            <ActionIcon size="sm" variant="subtle" color="green">
              <Play size={14} />
            </ActionIcon>
          </Tooltip>
          <ActionIcon size="sm" variant="subtle" color="gray">
            <Columns size={14} />
          </ActionIcon>
        </Group>
      </Group>

      {/* Split View */}
      <Group
        gap={0}
        style={{ flex: 1, overflow: "hidden", alignItems: "stretch" }}
      >
        {/* --- [ΑΛΛΑΓΗ 3: Εισαγωγή του Component <Editor />] --- */}
        <Box style={{ flex: 1, position: "relative" }}>
          <Editor
            height="100%"
            defaultLanguage="my-latex" // ΠΡΟΣΟΧΗ: Πρέπει να είναι ίδιο με το id στο register
            defaultValue={INITIAL_CODE}
            onMount={handleEditorDidMount} // Αυτό είναι το κλειδί για να τρέξουν τα παραπάνω
            options={{
              minimap: { enabled: true, scale: 0.75 },
              fontSize: 14,
              fontFamily: "Consolas, monospace",
              scrollBeyondLastLine: false,
              automaticLayout: true,
            }}
          />
        </Box>

        {/* PDF Preview Area (Δεξιά) */}
        <Box
          w="50%"
          h="100%"
          bg="dark.6"
          style={{
            borderLeft: "1px solid var(--mantine-color-dark-5)",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <Group
            justify="space-between"
            px="xs"
            py={4}
            bg="dark.7"
            style={{ borderBottom: "1px solid var(--mantine-color-dark-5)" }}
          >
            <Text size="xs" fw={700} c="dimmed">
              PDF PREVIEW
            </Text>
            <ActionIcon size="xs" variant="transparent">
              <Maximize2 size={12} />
            </ActionIcon>
          </Group>
          <Box
            style={{
              flex: 1,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
            bg="gray.7"
          >
            {/* Placeholder για το PDF */}
            <Box
              w="80%"
              h="90%"
              bg="white"
              p="xl"
              style={{
                boxShadow: "0 4px 12px rgba(0,0,0,0.3)",
                color: "black",
                overflowY: "auto",
              }}
            >
              <Text size="xl" fw={700} mb="md">
                1 Εισαγωγή
              </Text>
              <Text size="sm">Αυτό είναι ένα παράδειγμα αρχείου LaTeX.</Text>
              <Box
                my="xl"
                ta="center"
                fs="italic"
                style={{ fontFamily: "serif" }}
              >
                E = mc²
              </Box>
            </Box>
          </Box>
        </Box>
      </Group>
    </Stack>
  );
};

// 4. Status Bar
const StatusBar = () => (
  <Group
    h={24}
    px="xs"
    justify="space-between"
    bg="blue.8"
    c="white"
    style={{ fontSize: "11px", userSelect: "none" }}
  >
    <Group gap="lg">
      <Group gap={4} style={{ cursor: "pointer" }}>
        <TerminalSquare size={12} />
        <Text size="xs" inherit>
          Ready
        </Text>
      </Group>
      <Text size="xs" inherit>
        Ln 12, Col 4
      </Text>
    </Group>
    <Group gap="lg">
      <Text size="xs" inherit>
        UTF-8
      </Text>
      <Text size="xs" inherit>
        LaTeX
      </Text>
      <Group gap={4}>
        <Database size={10} />
        <Text size="xs" inherit>
          DataTex DB: Connected
        </Text>
      </Group>
    </Group>
  </Group>
);

const handleEditorDidMount = (_editor: any, monaco: any) => {
  // 1. Καταχώρηση της γλώσσας LaTeX
  monaco.languages.register({ id: "my-latex" });
  monaco.languages.setMonarchTokensProvider("my-latex", latexLanguage);
  monaco.languages.setLanguageConfiguration("my-latex", latexConfiguration);

  // 2. Καταχώρηση και εφαρμογή του Θέματος
  monaco.editor.defineTheme("data-tex-dark", dataTexDarkTheme);
  monaco.editor.setTheme("data-tex-dark");
};

// --- Main App ---

export default function App() {
  const [activeActivity, setActiveActivity] = useState<SidebarSection>("files");

  return (
    <MantineProvider theme={theme} defaultColorScheme="dark">
      <AppShell
        header={{ height: 35 }}
        navbar={{ width: 300, breakpoint: "sm", collapsed: { mobile: true } }}
        footer={{ height: 24 }}
        padding={0}
      >
        {/* Header */}
        <AppShell.Header withBorder={false} bg="dark.9">
          <Group
            h="100%"
            px="md"
            justify="space-between"
            style={{ borderBottom: "1px solid var(--mantine-color-dark-6)" }}
          >
            <Group>
              <Group gap={6}>
                <Database size={18} color="#339af0" />
                <Text fw={700} size="sm" c="gray.3">
                  DataTex{" "}
                  <Text span size="xs" c="dimmed" fw={400}>
                    v2.0
                  </Text>
                </Text>
              </Group>
              <Group ml="xl" gap={4} visibleFrom="sm">
                {[
                  "File",
                  "Edit",
                  "Selection",
                  "View",
                  "Go",
                  "Run",
                  "Terminal",
                  "Help",
                ].map((label) => (
                  <Button
                    key={label}
                    variant="subtle"
                    color="gray"
                    size="compact-xs"
                    radius="sm"
                  >
                    {label}
                  </Button>
                ))}
              </Group>
            </Group>
            <Group>
              <TextInput
                placeholder="Search DataTex..."
                leftSection={<Search size={12} />}
                size="xs"
                styles={{
                  input: {
                    height: 24,
                    minHeight: 24,
                    backgroundColor: "var(--mantine-color-dark-8)",
                    borderColor: "var(--mantine-color-dark-5)",
                  },
                }}
              />
            </Group>
          </Group>
        </AppShell.Header>

        {/* Layout */}
        <AppShell.Main
          bg="dark.9"
          style={{
            display: "flex",
            flexDirection: "column",
            height: "100vh",
            paddingTop: 35,
            paddingBottom: 24,
          }}
        >
          <Group
            gap={0}
            h="100%"
            align="stretch"
            style={{ flex: 1, overflow: "hidden" }}
          >
            <ActivityBar
              active={activeActivity}
              setActive={setActiveActivity}
            />
            <Box
              w={250}
              h="100%"
              style={{ borderRight: "1px solid var(--mantine-color-dark-6)" }}
            >
              <SidebarContent activeSection={activeActivity} />
            </Box>
            <Box style={{ flex: 1, minWidth: 0 }}>
              <EditorArea />
            </Box>
          </Group>
        </AppShell.Main>

        <AppShell.Footer withBorder={false} p={0}>
          <StatusBar />
        </AppShell.Footer>
      </AppShell>
    </MantineProvider>
  );
}
